(define (problem ER-Full)
	(:domain attack_planning)
	(:init
		(connected host-0 host-3)
		(connected host-1 host-4)
		(connected host-1 host-2)
		(connected host-2 host-3)
	    (connected host-3 host-7)
		(connected host-2 host-5)
		(network_access host-1)
		(has_vulnerability host-5 CVE-2014-7169)
		(connected host-0 host-4)
		(has_file host-5 File)
		(compromised host-2)
		(compromised host-4)
		(compromised host-3)
		(compromised host-5)
		(connected host-0 host-0)
		(compromised host-1)
		(has_file host-7 File)
		(connected host-4 host-5)
		(user_access host-3)
		(connected host-5 host-7)
		(connected host-4 host-0)
		(has_file host-3 File)
		(read_access host-7)
		(connected host-1 host-0)
		(connected host-3 host-1)
		(user_access host-0))
	(:goal
		(and
<HYPOTHESIS>
))
)
